### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by KnightAndroid** [wyjsonGo/GoRouter#48]
有时候重新运行报 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/xxx/xxx/xxxx
重新clean又可以了

**Comment by wyjsonGo** [comment]
贴一下报错信息和Android版本.

**Comment by KnightAndroid** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/knight/kotlin/module_home/fragment/HomeArticleFragment;
                                                                                                    	at com.wyjson.router.module.route.ModuleHome$$Route.loadRouteForModule_homeGroup(ModuleHome$$Route.java:38)
                                                                                                    	at com.wyjson.router.module.route.ModuleHome$$Route.-$$Nest$mloadRouteForModule_homeGroup(Unknown Source:0)
                                                                                                    	at com.wyjson.router.module.route.ModuleHome$$Route$1.load(ModuleHome$$Route.java:55)
                                                                                                    	at com.wyjson.router.core.RouteCenter.getCardMeta(RouteCenter.java:69)
                                                                                                    	at com.wyjson.router.core.RouteCenter.assembleRouteCard(RouteCenter.java:242)
                                                                                                    	at com.wyjson.router.GoRouter.go(GoRouter.java:362)
                                                                                                    	at com.wyjson.router.model.Card.go(Card.java:116)
                                                                                                    	at com.wyjson.router.model.Card.go(Card.java:81)
                                                                                                    	at com.knight.kotlin.module_main.activity.MainActivity.initFragments(MainActivity.kt:67)
                                                                                                    	at com.knight.kotlin.module_main.activity.MainActivity.initView(MainActivity.kt:33)
                                                                                                    	at com.knight.kotlin.module_main.activity.MainActivity.initView(MainActivity.kt:24)
                                                                                                    	at com.knight.kotlin.library_base.activity.BaseActivity.onCreate(BaseActivity.kt:144)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8214)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8202)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4038)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4252)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8673)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

鸿蒙系统 3.0   Android 10

**Comment by wyjsonGo** [comment]
[issues/576](https://github.com/alibaba/ARouter/issues/576)
[issues/820](https://github.com/alibaba/ARouter/issues/820)
